// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarPdEgSnyVOhwVej-ntT_nbCbS_S3Olo',
    appId: '1:696794662971:web:8b25073839fb04e4d0f41e',
    messagingSenderId: '696794662971',
    projectId: 'appjam-61a83',
    authDomain: 'appjam-61a83.firebaseapp.com',
    storageBucket: 'appjam-61a83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDQcAdd_RyH04hya4FGqj0bl9y3OrfV0',
    appId: '1:696794662971:android:d389fed21174a019d0f41e',
    messagingSenderId: '696794662971',
    projectId: 'appjam-61a83',
    storageBucket: 'appjam-61a83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKaa4JofRe03psqDBR4cPipl_MRqteDbk',
    appId: '1:696794662971:ios:92f6a80f6b977040d0f41e',
    messagingSenderId: '696794662971',
    projectId: 'appjam-61a83',
    storageBucket: 'appjam-61a83.appspot.com',
    iosClientId: '696794662971-di18nifpmovtjtuuh02b04vov9g3boit.apps.googleusercontent.com',
    iosBundleId: 'com.example.appJam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKaa4JofRe03psqDBR4cPipl_MRqteDbk',
    appId: '1:696794662971:ios:92f6a80f6b977040d0f41e',
    messagingSenderId: '696794662971',
    projectId: 'appjam-61a83',
    storageBucket: 'appjam-61a83.appspot.com',
    iosClientId: '696794662971-di18nifpmovtjtuuh02b04vov9g3boit.apps.googleusercontent.com',
    iosBundleId: 'com.example.appJam',
  );
}
